### ISSUE TITLE
Add <Delvana>

### ISSUE THREAD

**Issue by DelvanonLeader** [Baelyk/renegade-map#11]
![political](https://user-images.githubusercontent.com/31907830/30355369-994f42c0-9865-11e7-9531-673ea760752b.png)

**Comment by Baelyk** [comment]
FYI in the future you should leave out the < and > around you nation name.
Also, unless you respond otherwise I am going to do this (the circle was a bit unclear):
![30355369-994f42c0-9865-11e7-9531-673ea760752b](https://user-images.githubusercontent.com/20310200/30504797-6bda3e4e-9a36-11e7-8927-8a05353cb1d4.jpeg)

**Comment by Baelyk** [comment]
I'm actually gonna put this on hold for now. I know its not "official" yet, but I'd like there to be some activity requirements. 
You can appeal this by re-opening the issue at any time.
